### ISSUE TITLE
Using S3_UPLOADS_BUCKET_URL uses default upload location on new uploads

### ISSUE THREAD

**Issue by oscarcardoso** [humanmade/S3-Uploads#131]
When using the S3_UPLOADS_BUCKET_URL to define the location, when you try to upload a new image it uploads it to the default location `[bucket name].s3.amazonaws.com/uploads/[file path]`.

I tested by setting the constant to `https://[bucket name].s3.amazonaws.com/blog/wp-content` since my images where already uploaded to that folder. The images worked fine, but when trying to upload a new one, it uploaded it to /uploads/2016/10 folder in my bucket.

I will copy the files to the plugin default location, but it would make more sense if you define this constant to use it as the destination folder for new uploads too.

Thanks!

**Comment by rmccue** [comment]
This indeed seems like a potential bug. `filter_upload_dir` only [replaces `WP_CONTENT_DIR`](https://github.com/humanmade/S3-Uploads/blob/508239ba6afb1ee4191a6f61c6d0c1834aca9b21/inc/class-s3-uploads.php#L86), rather than the full upload directory.

@joehoyle Is this intentional behaviour to include the `/uploads/...` part?

**Comment by joehoyle** [comment]
This was intentional, but somewhat old behaviour. I took the decision back in the day to put all things in `uploads` to allow other directories to be created at a level above if needed, similar to how some plugins try to do with the `WP_CONTENT_DIR`. For example, a plugin may want to put a `backups` directory in the WP_CONTENT_DIR and write it's backups to that, so I didn't want to restrict the use of S3-Uploads to only the uploads directory. That _might_ not have been the best idea, but this is intentional. We might want to provide a way users to work around this however.

**Comment by xjlin0** [comment]
So if I create some files under some other folders under  WP_CONTENT_DIR, will S3-Uploads plug-in copy the folder structures to S3 as well?

**Comment by joehoyle** [comment]
@xjlin0 by default no it won't do that - however it just stores uploads on s3 in a subdir in the case you did want to do that via other means.
