### ISSUE TITLE
Conflict with UpdraftPlus

### ISSUE THREAD

**Issue by timothyjensen** [humanmade/S3-Uploads#144]
I am attempting to send UpdraftPlus backups to AWS, but when testing the connection between UpdraftPlus and AWS I see this error https://cl.ly/201G3m32040L.  The error disappears when I deactivate the S3 Uploads plugin.  How do you recommend resolving this issue?

**Comment by joehoyle** [comment]
I think this is because the backups plugin that can send files to S3 is meant to use an older version of the AWS SDK, but the S3 Uploads one is being used instead. If that _is_ the case, it would be best if updraftplus updated their plugin to use v3 of the AWS SDK. However, there's unfortunately not really any inherent way to fix this as both plugins use the AWS SDK, and only 1 can ever be loaded at a time, so both plugins needs to be compatible with the same version.

**Comment by geoffmyers** [comment]
@timothyjensen Were you able to find a solution to this issue (temporary hack or long-term fix)? Please let me know your thoughts. Thanks!

**Comment by timothyjensen** [comment]
@geoffmyers Unfortunately no, but I admit that I didn't push it too hard with Updraft.  I ended up switching to the AWS S3 plugin by Delicious Brains and have has not issues since then.  Makes me wonder if the issue wasn't with Updraft after all?

**Comment by joehoyle** [comment]
It's a somewhat unsolvable compatibilty problem I think. If 2 plugins want to use different versions of the AWS SDK, then it's not really doable. S3 Uploads tries to keep to the latest version of the AWS SDK. I'm going to close this out, but thanks for noting :)
