### ISSUE TITLE
All media files getting uploaded rather than just desired ones

### ISSUE THREAD

**Issue by jgreaves8** [humanmade/S3-Uploads#173]
I'm using WPAllImport to import WooCommerce products, the problem is that when I upload the CSV that the plugin is going to parse, the plugin can't find the CSV anymore (because it's on S3)

Does this sound like something that's do-able?

If someone could point me in the right direction I'd be happy to try to figure it out myself but I'm flying blind atm.

Regards

J

**Comment by michaelrimbach** [comment]
Follow

**Comment by rmccue** [comment]
This might be possible. The key part where S3 Uploads hooks into WP is the `upload_dir` filter. This replaces your regular upload directory (like `~/wp-content/uploads/`) with the S3 stream protocol (`s3://bucket/`). To have more complex behaviour like this, you can hook into `upload_dir` after S3 Uploads has changed the URL, and change it back to something else.

However, you don't get a huge amount of context from WP on this filter, so it may not be entirely possible to do what you want to do here. You could potentially write your own stream wrapper and use that instead, then pass data through to S3 Uploads as needed.

That said, maybe we can solve the actual issue: why can't WPAllImport find the CSV? What functions is it using here? Stream wrappers are supported by most PHP functions, so it's surprising that it doesn't even want to attempt to read it.

**Comment by devowhippit** [comment]
We created an MU Plugin for this issue that would just deactivate S3 Uploads when using WP All Import/Export. This seems to be fine because there is no need for it to be active other than when files are being imported into the media directory.

Not sure how this would work for imported content with attachments, however.

https://github.com/CityOfNewYork/ACCESS-NYC/blob/env/accessnyctest/wp-content/mu-plugins/s3-uploads-compatibility.php

The article linked mentions mentions another option by setting the base directory for WP All Import . We did try it but it didn't seem to work correctly in some of our tests. Also, Soflyy doesn't support changing this constant.

```
define('WP_ALL_IMPORT_UPLOADS_BASE_DIRECTORY', '../wpallimport');
```

https://www.affiliatewebdesigners.com/2015/06/02/using-amazon-s3-to-store-your-affiliate-product-images/

**Comment by joehoyle** [comment]
Thanks for documenting your solution @devowhippit

**Comment by lionelyoung** [comment]
Looks like the MU plugin moved here: https://github.com/CityOfNewYork/ACCESS-NYC/tree/main/wp-content/mu-plugins/wp-s3-all-import-compatibility

**Comment by devowhippit** [comment]
We created a separate mu-plugin package for this; https://packagist.org/packages/nyco/wp-s3-all-import-compatibility
