### ISSUE TITLE
Add the plugin to Wordpress.com?

### ISSUE THREAD

**Issue by ArondeParon** [humanmade/S3-Uploads#175]
Hi there!

Is there a reason for not submitting this plugin to the main Wordpress.com database? 
We use wpackagist.com to handle our plugin dependencies and this would make things a lot easier :)

**Comment by rmccue** [comment]
This plugin is designed for use for advanced developers, and we don't provide full support for the plugin ([we have a specific support policy](https://engineering.hmn.md/projects/support/)). Because of this, it's not really applicable to the broad userbase of the WordPress.org plugins repository.

With that said, if you're using Composer, this plugin is [published on Packagist](https://packagist.org/packages/humanmade/s3-uploads) as `humanmade/s3-uploads`, so you should be able to use it pretty easily.
