### ISSUE TITLE
Support for secure images

### ISSUE THREAD

**Issue by danielbachhuber** [humanmade/S3-Uploads#2]
I'd like to use this to "securely" store images on S3 for a private site. What I'm thinking is that, when viewing the site, the image URLs would include the access token. The access token obviously would have a limited lifespan.

What do you think of this approach?

**Comment by steven-klein** [comment]
@danielbachhuber I know this is an ancient post, but it would be great to hear if you developed a working model for this.

**Comment by danielbachhuber** [comment]
> I know this is an ancient post, but it would be great to hear if you developed a working model for this.

I don't believe I did. Honestly, I don't recall any of the context for the original issue either.

**Comment by rmccue** [comment]
@steven-klein Rather than using ACLs, you're best off restricting the bucket entirely and [using signed URLs](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-presigned-url.html). Basically, you'd have a plugin generate them with a lifetime of (say) 6 hours, store in a cache, and regenerate them as needed using the AWS SDK.

The tough part, as @joehoyle mentions above, is changing the URLs in your content. These are saved into the content with their full URLs; pulling them back out requires heuristically finding them, rather than just filtering them. ([Gaussholder](https://github.com/humanmade/Gaussholder) does a similar content modification for images, which might be worth looking into.)

**Comment by steven-klein** [comment]
For what it's worth to anyone.  I was pretty successful at getting this to work with signed url by adding the following filters: **wp_get_attachment_url, wp_get_attachment_image_src, wp_calculate_image_srcset, wp_prepare_attachment_for_js**.  Each filter required it's own function that made use of another function that accepted a single url as a parameter, and returned a signed version of the url.  

A little caching on the signed url generation would go a long way, but It wasn't a high priority for me, so I have yet to implement it.

**Comment by joehoyle** [comment]
Going to close this out as I don't think this will ever be part of this plugin, but an addon plugin would certainly be a good idea.
