### ISSUE TITLE
Contact Form 7 File Upload Issues

### ISSUE THREAD

**Issue by Binternet** [humanmade/S3-Uploads#206]
When Implementing a File input on Contact Form 7, the S3 upload process just freezes and timeouts after 30 seconds - for a 30kb file! 

I've increased `max_execution_time` to `300 seconds` (5 minutes) and it still time outs some obviously something's with the upload process.

**Comment by joehoyle** [comment]
As it happens I too have run into this. The problem is that cf7 tries to keep creating directories until it find's one that doesn't exist. The problem: S3 doesn't _have_ directories, so we always tell `mkdir` that a DIR exists, to say "...sure, just write to it". The problem is this kinda of code, which I happened to open a PR for CF7 on a fork here: https://github.com/humanmade/contact-form-7/pull/1

**Comment by Binternet** [comment]
Thanks, [This PR actually fixes the issue](https://github.com/humanmade/contact-form-7/pull/1)

**Comment by alvsconcelos** [comment]
Hey guys, if anyone is having problems with this question like me, here it goes: I've solved without any modifications on the plugin. All i need to do is add a constant on Wordpress wp-config.php file specifying a custom directory for the contact form uploads. It bypasses the s3 uploads filters.
`define('WPCF7_UPLOADS_TMP_DIR', 'wpcf7_uploads');`
