### ISSUE TITLE
Incompatible with other AWS SDK Plugin

### ISSUE THREAD

**Issue by creativekindle** [humanmade/S3-Uploads#299]
I'm getting this error from another plugin using AWS SDK about s3-uploads:

(line: 374, file: /home/.../public_html/wp-content/plugins/s3-uploads/lib/aws-sdk/Aws/ClientResolver.php)

Error message: S3 Error: Failed to initialise: Missing required client configuration options: 
version: (string)

A "version" configuration value is required. Specifying a version constraint ensures that your code will not be affected by a breaking change made to the service. For example, when using Amazon S3, you can lock your API version to "2006-03-01".
  
Your build of the SDK has the following version(s) of "s3": * "2006-03-01"
  
You may provide "latest" to the "version" configuration value to utilize the most recent available API version that your client's API provider can find. Note: Using 'latest' in a production application is not recommended.
  
A list of available API versions can be found on each client's API documentation page: http://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html. If you are unable to load a specific API version, then you may need to update your copy of the SDK. (line: 374, file: /home/.../public_html/wp-content/plugins/s3-uploads/lib/aws-sdk/Aws/ClientResolver.php)

**Comment by roborourke** [comment]
@creativekindle sorry to hear that. It's tricky because this plugin will kick in any time there's a read or write to your uploads directory. My hunch is that UpdraftPlus will need to read your uploads to perform a backup so I'm not sure these plugins will be compatible until they update their version of the AWS SDK.

I might be wrong depending on how the backup process and upload are handled by that plugin but I'm not sure it's something we can fix.

**Comment by theasteve** [comment]
@creativekindle Check this post: https://github.com/humanmade/S3-Uploads/issues/316
