### ISSUE TITLE
Bandwidth and dual NICs with self hosted S3

### ISSUE THREAD

**Issue by menathor** [humanmade/S3-Uploads#312]
Hi guys!

I'm just trying to figure out how the plugin works in terms of bandwidth. I want to offload my users' files to my self hosted minio server to 

a) save space on my web server

b) improve page speeds by using my minio install as a cdn

c) minimise bandwidth usage on my web server by having uploads go from clients' browsers directly to the S3 bucket. 

From what I've read, it seems like a and b are no problem (unless I've misunderstood) but I'm still a little uncertain about c.

For example, if user is uploading a 25mb file, does that mean pushing all 25mb to my web server first, which will then re-transmit the 25mb to the S3 server? Or is there some magic that will allow  traffic to go straight from the browser to the S3 bucket?

If not, is there any way of setting up the plugin to push data via a second NIC (private IP)? The web server and minio server have a private LAN between them- using that to push files means external bandwidth won't be affected.

Or do you think something like NFS would be better for what I'm trying to do? I'd definitely prefer to do it via S3 if possible, just not sure how to go about it. 

Thanks!

**Comment by rmccue** [comment]
Hi! This is only kind-of possible due to the way that uploads work. For some context, I'll dive into that a bit:

Basically, when you upload a file in your browser, it sends a POST request to the server and includes the data for the file that you're uploading to the server. It looks something like:

```
POST /wp-admin/async-upload.php HTTP/1.1
Content-Type: multipart/form-data; boundary=----foo

----foo
Content-Disposition: form-data; name="your-image.jpg"

<binary JPEG data here>
```

This passes through any reverse proxies you may have and eventually gets to PHP. PHP then parses the request and works out that a file has been sent, and handles it automatically for you by extracting that data out and saving it to a temporary directory. (Specifically, [`upload_tmp_dir`](https://www.php.net/manual/en/ini.core.php#ini.upload-tmp-dir).) PHP then runs WordPress, which runs S3 Uploads. When WordPress starts handling the upload, PHP has already saved the request data to a temporary file, so WordPress just needs to rename it into place.

S3 Uploads hooks in at this spot, and tells WordPress to move the file to `s3://your-bucket/path...` instead of a local path. PHP sees this `s3://` protocol and passes the data to the S3 handler internally (part of the AWS SDK), which then uploads the data to S3 (or compatible service).

> For example, if user is uploading a 25mb file, does that mean pushing all 25mb to my web server first, which will then re-transmit the 25mb to the S3 server?
> Or is there some magic that will allow traffic to go straight from the browser to the S3 bucket?

Basically, yes, it has to be done this way. The uploaded file is part of the user's request data being sent to your server, so there's not really† any way to avoid this.

† There kind of is. Essentially, you need a reverse proxy between the user and PHP which will take the data and push it to S3 instead of handling it in PHP. This is something you'd need to build a custom integration for, and S3 Uploads won't really work for that.

Note that the bandwidth is still used by some part of your network, so there's essentially no way to avoid this.

> a) save space on my web server

This shouldn't be an issue, as files are sent to `/tmp`,  and your system will typically clean up this content itself. (On some systems, `/tmp` is actually backed by RAM rather than disk as well.)

Additionally, I believe WordPress deletes the temporary files after it has handled it, but not entirely certain on that.

> The web server and minio server have a private LAN between them- using that to push files means external bandwidth won't be affected.

If that's the case, you've already minimised your data usage, as you'll only pay for the data coming in from the user once.

**Comment by rmccue** [comment]
> † There kind of is. Essentially, you need a reverse proxy between the user and PHP which will take the data and push it to S3 instead of handling it in PHP. This is something you'd need to build a custom integration for, and S3 Uploads won't really work for that.

Note: I would strongly recommend against trying this; I've built one of these systems, and it was a nightmare to integrate. It required patching PHP's internals in order to ensure compatibility with existing code. In our case, it was a platform requirement to handle it, otherwise we wouldn't have bothered.

**Comment by menathor** [comment]
Awesome, thanks for the detailed info. So I guess it's not much different to a NFS or iSCSI setup in terms of bandwidth... Would you say it's more reliable? Shared folders can be a bit hit and miss

**Comment by rmccue** [comment]
We run it in production with pretty high traffic/etc on enterprise sites, so it's pretty reliable. NFS/iSCSI isn't really usable for S3, as S3 is object storage rather than block storage; I can't speak to a custom Minio server though, your requirements may be different.

Closing this out, as it's not an issue with S3 Uploads, but feel free to comment with anything further.
