### ISSUE TITLE
2.1.0-RC2 tries to require autoload.php from wrong location when installed via composer

### ISSUE THREAD

**Issue by OscarBarrett** [humanmade/S3-Uploads#313]
When installed via composer, the plugin ends up in `wp-content/plugins/s3-uploads` and other dependencies (such as the aws sdk) end up in `<root>/vendor`.

`s3-uploads.php` calls `require_once dirname( __FILE__ ) . '/vendor/autoload.php';` [here](https://github.com/humanmade/S3-Uploads/blob/f17559cba87e0a0a0191a747f62c74dbde60208d/s3-uploads.php#L21) but no vendor folder exists within the s3-uploads plugin folder.

**Comment by gurumark** [comment]
What's the solution to this issue?

**Comment by rmccue** [comment]
Updating to 2.1.0 final and loading Composer's autoload file yourself should solve these issues.

**Comment by gurumark** [comment]
Unfortunately, it did not. I am using 2.1.0.

**Comment by mrpatrick** [comment]
I'm having the same issue

**Comment by dnicinskiCTC** [comment]
@rmccue Same issue here too. Is this issue going to be fixed soon? The vendor folder is not getting added.

**Comment by JeffGuKang** [comment]
I solved with `composer install` in `plugins/S3-Uploads`

**Comment by codeagencybe** [comment]
Yes, installation via composer fails too. 
But as @OscarBarrett already pointed out, the folder "vendor" is actually created in your root folder (same level as wp-config) and thus the cause for failure. 
If you move the folder vendor into the plugin folder, the problem is solved. 
So it's just an issue of a wrong path somewhere it seems.
