### ISSUE TITLE
Conflict with W3 Total Cache

### ISSUE THREAD

**Issue by ostensiblycool** [humanmade/S3-Uploads#328]
After updating W3TC I get a white screen of death, since both plugins are loading the S3 SDK. I'd like to continue using both plugins, is there a plan to fix this errror?

**Comment by zocoloco** [comment]
I'm having a similar problem SDK version error - with UpdraftPlus. Suggestions?

**Comment by johnbillion** [comment]
This plugin conditionally loads the AWS SDK if the class doesn't exist, therefore it's compatible with other plugins and libraries that do the same.

W3 Total Cache doesn't do this, which makes it incompatible with other plugins that do. You should contact the developer of W3 Total Cache about loading the library properly, or you should [define the `W3TC_SKIPLIB_AWS` constant](https://github.com/W3EDGE/w3-total-cache/blob/49dfa53324d1884796a910d27bf1647abd8227bf/CdnEngine_S3.php) which instructs W3 Total Cache not to load the AWS SDK.

I haven't checked, but I imagine it's the same issue for UpdraftPlus.

**Comment by ostensiblycool** [comment]
Ok thanks I will follow up. Thanks so much. Your plugin rocks.

**Comment by zocoloco** [comment]
The first person who posted has the conflict issue with W3 Total Cache. I'm having the issue with a different plugin - UpdraftPlus. You said S3-Uploads loads the AWS SDK conditionally...but I believe it checks to see if the SDK exists during installation, and if not, it installs the version it require. If the second plugin isn't calling the SDK at that point, it will see it as non-existent. Then the version S3-Uploads installs becomes the constant that is used for all plugins, rather than just S3-Uploads. If a different plugin uses an older version of the SDK, the one S3-updates requires then supersedes it. 

From a troubleshooting perspective, this is what makes sense to me. For example:
**TEST ONE**: one plugin activated requiring the AWS SDK:
- UpdraftPlus
_results_: everything works as expected
**TEST TWO**: two plugins activated both requiring the AWS SDK:
- UpdraftPlus
- S3-Uploads
_results_: UpdraftPlus stops working
**TEST THREE**: two plugins activated both requiring the AWS SDK:
- UpdraftPlus
- WP Offload Media Lite
_results_: everything works as expected

If you define the W3TC_SKIPLIB_AWS constant, as you suggested, my guess is W3 Total Cache and BackupPlus will both fail, because from what I read, they use an older version of the AWS SDK for backwards compatibility, 

Your thoughts? Trying to make sense of this so both plugins can be used simultaneously.

**Comment by wwwXpert** [comment]
It's an annoyance from sloppy coding.
Work-around: Only activate one plugin that uses AWS SDK at a time.

De-activate w3 total cache.
Activate the one AWS plugin that you want to setup.
Configure, test, deploy on AWS.
De-activate the one AWS plug-in.
Re-activate w3 total cache plugin and configure the AWS part in w3 total cache.

All plugins that use open source libraries should check upon activation if the classes already exist. Don't declare them if they already exist.
```
if ( !class_exists( 'MyClass' ) ) {
	class MyClass {
...
```
AWS SDK for PHP
https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html
