### ISSUE TITLE
Possibility to ignore files by name or pattern

### ISSUE THREAD

**Issue by JJPragmatic** [humanmade/S3-Uploads#337]
Is it currently possible to ignore files by either name or pattern from syncing with s3?

**Comment by sawanoboly** [comment]
I have same issues.

There are plugins that create export files (such as wp-filemanager plugin) or work files (* .tmp) under the uploads directory, so I want to exclude them.
It would be helpful if it could be excluded by directory matching or extension matching. any options for this?

**Comment by rmccue** [comment]
Hi! We're not planning on adding this functionality any time soon.

Due to the way that uploads in WordPress work, it's a significant amount of work to do this. S3 Uploads doesn't receive the filename or path when it first hooks in, so this would need handling deep within the stream wrapper.

If there are any filters we can add to S3 Uploads to better support this use case, we're happy to add those, but we're unlikely to add the feature itself (see [our support policy](https://engineering.hmn.md/projects/support/) for more information).
