### ISSUE TITLE
Super plugin, but question

### ISSUE THREAD

**Issue by pkiula** [humanmade/S3-Uploads#338]
Hello. This looks very promising, but I have a question. We don't need plugins etc. I can even put this in our functions.php if needed. But it's important for us to have the following: 

1. Before saving, have the media optimised by "EWWW" plugin which also automates the generation of the corresponding WebP for all media auto-sizes. 

2. Have the media saved in the permalink structure of our site. With over 15K photos, this becomes paramount to search easily in the future. So instead of the usual year/month URLs, we'd like `/post_type/category/postname/media1.jpg` etc. The "Custom Uploads Dir" plugin already does this. 

3. Third, have these files COPIED (not only saved on S3, but have a copy saved there), with the appropriate cache-control headers etc. 

4. Auto-generate a CDN URL from the S3 version. Anything that gets saved inside the Wordpress DB as content should use our CDN URL, or if the original media path is used, then we'd like our `the_content()` etc to auto-flilter the URLs and publish the CDN URLs. 

At the moment we have #3 and #4 being performed by S3 Offload plugin, but it's intrusive and takes over URL generation too (#2 above). Will ditching the Offload plugin and using this simpler script allow us to achieve the above? 

Many thanks! (Btw, very thorough and patient explanation of the code!)

**Comment by joehoyle** [comment]
1 & 2 are not specific to S3 Uploads, and look to be general WordPress media problems. (Note on webp). Those approaches should work fine with S3 Uploads.

3: This use-case is not supported by this plugin, S3-Uploads is to _replace_ your local uploads directory with one on s3.

4. This can be done in S3 uploads by setting the `S3_UPLOADS_BUCKET_URL` do you CDN's URL. All file urls will then use this value instead of the S3 URL.
