### ISSUE TITLE
Question about filesystem upload

### ISSUE THREAD

**Issue by fabioce** [humanmade/S3-Uploads#347]
Hi,
I need to understand a little important thing:
after the correct installation and activation of the plugin, after the sync of the old upload library,
all new uploads goes directly to S3 or goes through local filesystem and after sync to S3?
My question is:
After the sync of all upload library, is possible to delete upload folder?
Thanks

**Comment by rmccue** [comment]
>  all new uploads goes directly to S3 or goes through local filesystem and after sync to S3?

Uploads are sent as the HTTP request body to the site. PHP then saves this into `/tmp` automatically. WordPress would usually then move those files to `wp-content/uploads/`, but S3 Uploads replaces this, and uploads them to S3.

So, the files will be saved to the `/tmp` directory on the local filesystem, but otherwise will never be written to the filesystem. (This is unavoidable.)

>  After the sync of all upload library, is possible to delete upload folder?

Not directly; you'll have to edit the database if the URLs are changing. You can also handle the routing to keep the URLs the same but point to an S3 origin, which won't require a database update.
