### ISSUE TITLE
Slow post.php?post=1&action=edit on Post Edit

### ISSUE THREAD

**Issue by leowebguy** [humanmade/S3-Uploads#366]
Hey Guys,
Thanks for this amazing plugin!
I came to notice in my recent projects that after activating S3 Upload and uploading assets; and editing any Post (with or without VC) > /wp-admin/post.php?post=1&action=edit is taking 2min+ to fully load the page.
I tried updating S3-Uploads, Cache Control, Heartbeat... but it only works when I turn off S3-Uploads. I believe this is related to admin-ajax.php not sure.
Here are a couple screens: 
![Screen Shot 2019-12-13 at 4 43 40 PM](https://user-images.githubusercontent.com/8460020/70834582-b2e15d00-1dc8-11ea-9ab5-8868e06ee965.png)
![Screen Shot 2019-12-13 at 4 45 16 PM](https://user-images.githubusercontent.com/8460020/70834586-b5dc4d80-1dc8-11ea-97d9-52b34300c5d4.png)

**Comment by rmccue** [comment]
This is probably due to the backend connecting to S3 to load something from uploads on page view. I'd recommend using performance tooling to dig further into the request and investigate.

Note that [we can't offer detailed support](https://engineering.hmn.md/projects/support/), but if you find a bug, happy to look into it.
