### ISSUE TITLE
Manual install package

### ISSUE THREAD

**Issue by heathera2016** [humanmade/S3-Uploads#389]
Hi
First of all, thanks for your great works! I really appreciate it.
I have a suggestion.
I hope there's whitelist or blacklist folder which should be uploaded or vice versa.
Some plugins saved their cache under Uploads folder, so I cannot exclude that folder. Any workaround this? :)
Plus, could you please add manual install package into one so that I can just add a plugin on frontend?
It would be great if the installation is easy like other plugins setup.
Thank you again.

Best regards,
Heathera

**Comment by joehoyle** [comment]
Hi @heathera2016,

No, there's no way to do that, due to how S3 Uploads is architected. S3 Uploads replaces the whole uploads path, so there's no concept of "allowing some things to be stored in the origial uploads folder". Doing so would require a lot of rework of the plugin and use-case. S3 Uploads is most targetting to be used when you don't have the possibility to write to `content/uploads` due to no shared filesystem on multi-server setups etc.

**Comment by heathera2016** [comment]
Hi @joehoyle 
Thank you for your reply. Is there anyway to upload avatar folder of Buddypress?
Can you give some tips to tweak this plugin?
Many thanks!! :)
Have a wonderful day!

Best regards,
Heathera

**Comment by rmccue** [comment]
As noted, this is not supported out of the box. You're welcome to investigate yourself.

Please note [our support policy](https://engineering.hmn.md/projects/support/) as well. :)

**Comment by heathera2016** [comment]
I see. I'm investigating myself and changed the rule from the scratch. I think there's no need for getID3 anymore as Wordpress updated this and does not need to copy to temp folder due to rename issue because it also had been changed. Many thanks for your reply :)
