### ISSUE TITLE
Too many request PUT, COPY, or LIST

### ISSUE THREAD

**Issue by heathera2016** [humanmade/S3-Uploads#390]
Hello!
Thank you for your plugin. I appreciate it.
After I enabled this plugin, and tested some uploading. After that, I found my bill that PUT, COPY, POST, or LIST requests are almost 2000 per day and GET and all other request are 1,000 per day. I think PUT, COPY, POST or LIST request are weird because I uploaded only 50~100 MAX. Are there any logs to check or workaround this?
Thank you for your help in advance.

Best regards,
Heathera

**Comment by joehoyle** [comment]
Hi @heathera2016,

It's possible you have some plugins that are reading a lot from the uploads directly, and that could be causing this.

**Comment by barros001** [comment]
I had the same issue, editing a page/post was super slow and I found out it was because of a combination of plugins (have a plug-in that loops through several images and does `file_exists` on them). The real issue here is S3-Uploads creates a new s3 protocol wrapper and some plugins out there will make calls to `file_exists`, `is_file`, etc, including `wp_upload_dir` which by default does check if upload directory exists. All of these low level file system calls would be "translated" into s3 api calls and sent over the network. 

This has a couple of potential problems, one being slowing down both admin and front end of the site due to multiple network calls to load a page and the other being your AWS bill could grow quite a bit depending on usage.

This seems like a design flaw with this plugin and I'm not entirely sure how to solve it. In my case I temporarily "patched" the offending plugin (I know I know, but I had to solve an immediate pain point) while I research another plugin I can replace S3-Uploads with.

**Comment by joehoyle** [comment]
> This seems like a design flaw with this plugin and I'm not entirely sure how to solve it. In my case I temporarily "patched" the offending plugin (I know I know, but I had to solve an immediate pain point) while I research another plugin I can replace S3-Uploads with.

This is the intentional design of this plugin. I'd recommend not using plugins that make excessive reads on the filesystem, that would be causing this -- but indeed, it sounds like this plugin does not suit your requirements.

I'd recommend you set up AWS Billing alerts if you are worried about this too. I don't see anything here that we'd change in the plugin though, so closing out.
