### ISSUE TITLE
Adds 10sec page load when used with Elementor

### ISSUE THREAD

**Issue by WeAreHaus** [humanmade/S3-Uploads#395]
When using clean WP install everything workes fine, but when I activate Elementor page builder it takes about 10 on every page load. Is there a hook or something I can deactivate?

**Comment by joehoyle** [comment]
I don't know that plugin, but it sounds like it is done a lot of filesystem activity in the uploads folder on each page load, which is why it will be very slow. It's considered bad-practice to be touching the uploads filesystem excessivly, especoally on page-load, so I'd imagine there's something the plugin is doing related to that.
