### ISSUE TITLE
Pure php possible instead of composer?

### ISSUE THREAD

**Issue by gitmko0** [humanmade/S3-Uploads#418]
Using composer, my concern in future proofing this.
composer require humanmade/s3-uploads

1. though i havent try installing s3-uploads yet, does it generate empty folders?
2. s3fs mounting s3 to disk system... what's the advange to use s3-uoloads over s3fs?

thx for the clarification. great work by the way.

**Comment by hubertnguyen** [comment]
s3 is not a real filesystem, so there are many issues related to using it as one. There's quite a bit of literature on the web. The shared experiences could save you a lot of time.

**Comment by joehoyle** [comment]
>though i havent try installing s3-uploads yet, does it generate empty folders?

I'm not sure exactly what you are asking here -- S3 doesn't have empty folders, and s3-uploads will essentially no-op any call to `mkdir()`.

> s3fs mounting s3 to disk system... what's the advange to use s3-uoloads over s3fs?

S3 Uploads is not entirely different to this approach. We believe writing the apadtor to S3 at the application level, and having access to all the debugging and networking at runtime is superior to a filesystem mount. If you do use s3fs, you'll likely still want to generate URLs that point directly to s3 rather than to the local webserver, which will need to proxy requests to s3.

**Comment by gitmko0** [comment]
possible to have pure php version of this so we can future proof and not use composer to install?

**Comment by joehoyle** [comment]
@gitmko0 no, that isn't something we want to undertake.
