### ISSUE TITLE
I dont want to keep a copy of file in local drive. just purely s3 upload / download. is this possible?

### ISSUE THREAD

**Issue by gitmko0** [humanmade/S3-Uploads#423]
Basically i dont want to keep another copy of file in local drive. just purely s3. is this possible?

**Comment by joehoyle** [comment]
This is exactly how s3 uploads already works, no files are stored on your local disk (apart from PHP’s internal use of /tmp) when using s3 uploads.

**Comment by gitmko0** [comment]
it doesnt work that way on my hosting side.
it is still storing things also on the local side

**Comment by joehoyle** [comment]
@gitmko0 in that case, it sounds like the plugin is not correctly configured. You can open a new issue if you can't get it to place files on S3. If you see files on S3 and local, you might be using a different plugin!

**Comment by gitmko0** [comment]
i'm seeing both files on s3 and local. it's humanmade s3 plugin... is there a hint if my other plugins are making this happening?
also i'm allocating disk space for each user using multisite. will the users be able to be limited by the number of byte size of each account with humanmade s3 installed?

**Comment by rmccue** [comment]
Just checking, you mean files within `uploads/` on your disk right? PHP will create files in your system temp dir when users upload files (which is unavoidable); WordPress then copies those directly to S3 though, it won't copy them to the on-disk uploads directory provided S3 Uploads is configured correctly.

> is there a hint if my other plugins are making this happening?

Any plugins using the correct APIs in WordPress (namely `wp_upload_dir()`) will work with S3 Uploads provided they're not using certain low-level PHP APIs; if they are, you'd see an error though, not files placed in the on-disk uploads directory.

It's most likely that S3 Uploads isn't configured correctly, and you're falling into one of the [short-circuits that cause S3 Uploads not to load](https://github.com/humanmade/S3-Uploads/blob/539d0c16d4fb778caeb4fd2b12f5718fb48baea0/s3-uploads.php#L24-L38), or is otherwise misconfigured.

> will the users be able to be limited by the number of byte size of each account with humanmade s3 installed?

No, you would need to write custom code for any size limits like this.
