### ISSUE TITLE
Images are not uploaded to S3 bucket

### ISSUE THREAD

**Issue by ThunderBoltEngineer** [humanmade/S3-Uploads#483]
I am using modified version of S3 Upload plugin in my Wordpress site for image offloading.
Removed the url rewriting part (url rewriting is currently done by htaccess) and moved the plugin under `config/wp-plugins/`.
It worked well so far but stopped working from a couple of months ago. When I try to upload an image, it is uploaded to the local `/upload` directory but not to the S3 bucket.
I am not sure why it stopped working - please help me resolve this issue.

**Comment by gsc89** [comment]
We have a similar issue with one new build were working on where JPG images only are not being processed but PNG images are processed fine. 

Can you confirm if this is happening to you on all image types?

**Comment by ThunderBoltEngineer** [comment]
@gsc89  It is happening on all image types.

**Comment by gsc89** [comment]
Ah ok not the same thing then, I know are issue is "something" to do with this and not missing PHP extensions etc because you can disable S3 and it works fine. I will have to keep digging on our issue thanks for confirming you weren't having the same issue.

**Comment by ThunderBoltEngineer** [comment]
Thank you!

**Comment by rmccue** [comment]
Hi @ThunderBoltEngineer! Please note [our support policy](https://engineering.hmn.md/projects/support/); we're unable to offer detailed support with debugging.

I would suggest starting with [one of the early failures](https://github.com/humanmade/S3-Uploads/blob/d58519b20a8983d79c98b3595c1a00f413f894b7/inc/namespace.php#L12-L26) to see if S3 Uploads is skipping load due to one of these cases failing.

Closing, but feel free to reopen if you identify any bugs.
