### ISSUE TITLE
Not working with WooCommerce X-Accel-Redirect or Force download method

### ISSUE THREAD

**Issue by haqueminhajul** [humanmade/S3-Uploads#612]
Hi,

Thanks for this wonderful lightweight application!

I installed your plugin and successfully configured it with DigitalOcean Spaces. However, it seems to have some issues with WooCommerce Downloadable Products when **File download method** in the WooCommerce Settings is set to **X-Accel-Redirect** or **Force download**.

It's giving me an error "**File not found**" on the frontend when trying to download the purchased items from customer's My Account Dashboard.

But changing the "File download method" settings to **Redirect only** works fine. _Which I don't want to use as a direct link to downloadable product files will compromise security._ 

Is there anything that can be done about it.

Awaiting your response.

Best,
Minhajul

**Comment by rmccue** [comment]
This depends on how your server has been set up, but X-Accel-Redirect would only work if you were serving S3 files through nginx, as it's specific to the behaviour of nginx. (Unfortunately, I don't know anything about the "force download" option.)

You may also be able to use the [private uploads functionality](https://github.com/humanmade/S3-Uploads#private-uploads) which will set the ACL for the file to private, and use signed URLs which expire after a given time.

Please also note we're unable to provide in-depth support per our support policy: https://engineering.hmn.md/projects/support/

I'm going to close this ticket out for now, but feel free to follow up if you have any further questions about implementing this.

**Comment by chvillanuevap** [comment]
I don't mean to reopen this issue, but I ran into the same problem recently while searching for a solution, and I wanted to share the patch I ended up using in case it helps someone else.

### Problem

When the S3 Uploads plugin is active, `wp_upload_dir()['basedir']` is rewritten to an `s3://` stream wrapper. WooCommerce's `WC_Download_Handler::parse_file_path()` attempts to rewrite known upload URLs (`wp_upload_dir()['baseurl']`) into filesystem paths using that value.

Because WooCommerce does not understand stream wrappers, it rewrites my HTTPS CDN URL into an `s3://` path, strips the scheme, and then reduces the path to something like:

```
/uploads/woocommerce_uploads/2020/11/example.pdf
```

WooCommerce then attempts filesystem operations (`filesize()`, `fopen()`, `readfile()`) on that path, which fails because the file does not exist on the local disk.

### Fix

The safest interception point I found is the `woocommerce_download_parse_file_path` filter, which runs at the very end of `WC_Download_Handler::parse_file_path()`. At this point WooCommerce has already mangled the path, so the fix simply restores the correct public HTTPS URL.

This does not modify WooCommerce core, WordPress core, or the S3 Uploads plugin; it’s a small compatibility patch for WooCommerce downloads.

```php
add_filter(
    'woocommerce_download_parse_file_path',
    function ( string $file_path, bool $remote_file ) : string {

        if (
            str_starts_with( $file_path, '/uploads/' )
            && defined( 'S3_UPLOADS_BUCKET_URL' )
            && str_contains( $file_path, '/woocommerce_uploads/' )
        ) {
            return rtrim( S3_UPLOADS_BUCKET_URL, '/' ) . $file_path;
        }

        return $file_path;
    },
    10,
    2
);
```
Returning an HTTPS URL forces WooCommerce to treat the file as remote during the download phase, allowing the browser to download the file directly from the CDN (Cloudflare in my case). My function assumes a CDN-backed setup, but the same approach should work if you return your bucket’s public HTTPS URL directly I think.

Hopefully this helps someone else who runs into the same edge case.

**Comment by chvillanuevap** [comment]
Adding a note here for posterity.

It seems the issue here is related to WooCommerce sometimes resolving S3-backed download URLs back to a local filesystem path. In our case this showed up with files under `wp-content/uploads/woocommerce_uploads/` (PDFs, downloadable ZIPs, reports, etc.) when those paths were backed by S3 via `s3://` and while using Force Download. Even though the files existed and were readable from S3, Woo would attempt local filesystem access and fail with “file not found”.

What worked for us was to make sure WooCommerce treated the URLs as remote. We normalized S3-backed downloadable URLs so they are stored as protocol-relative URLs, e.g.:
```
 //media.example.com/woocommerce_uploads/my-product/file.zip
```
instead of:
```
https://media.example.com/woocommerce_uploads/my-product/file.zip
```
This forces WooCommerce down the "remote file" code path in `WC_Download_Handler::parse_file_path`, even when using a CDN domain, and avoids any filesystem assumptions entirely.

We also enforced redirect fallback for downloads (required for ZIP files). Between those two changes, downloads backed by S3 have been stable for us in production for different file types.

Prototype code below for reference (a bit overengineered), but downloads are critical for our project and this has held up well:
```
class My_S3_Uploads {

	public function __construct() {

		add_action(
			'woocommerce_admin_process_product_object',
			[ $this, 'normalize_s3_downloadable_urls' ],
			PHP_INT_MAX
		);

		add_action(
			'woocommerce_update_options_products_downloadable',
			[ $this, 'enforce_wc_download_settings' ]
		);

		add_filter(
			'woocommerce_downloadable_products_settings',
			[ $this, 'customize_redirect_fallback_description' ]
		);
	}

	public function normalize_s3_downloadable_urls( WC_Product $product ) : void {

		$this->normalize_product_downloads( $product );

		if ( $product->is_type( 'variable' ) ) {
			foreach ( $product->get_children() as $variation_id ) {
				$variation = wc_get_product( $variation_id );
				if ( $variation ) {
					$this->normalize_product_downloads( $variation );
				}
			}
		}
	}

	private function normalize_product_downloads( WC_Product $product ) : void {

		if ( ! defined( 'S3_UPLOADS_BUCKET_URL' ) ) {
			return;
		}

		$downloads = $product->get_downloads();
		$changed   = false;

		foreach ( $downloads as $download_id => $download ) {
			$file_url = $download->get_file();

			if ( str_contains( $file_url, S3_UPLOADS_BUCKET_URL ) ) {
				$normalized = preg_replace( '#^https?:#i', '', $file_url );
				$download->set_file( $normalized );
				$downloads[ $download_id ] = $download;
				$changed = true;
			}
		}

		if ( $changed ) {
			$product->set_downloads( $downloads );
			$product->update_meta_data( '_downloadable_files', $downloads );
		}
	}

	public function enforce_wc_download_settings() : void {
		update_option( 'woocommerce_downloads_redirect_fallback_allowed', 'yes' );
	}

	public function customize_redirect_fallback_description( array $settings ) : array {

		foreach ( $settings as &$setting ) {
			if (
				isset( $setting['id'] ) &&
				'woocommerce_downloads_redirect_fallback_allowed' === $setting['id']
			) {
				$setting['desc_tip'] .= ' ' . sprintf(
					'<strong>%s</strong>',
					__( 'This option is automatically enforced by our S3 Uploads customization.', 'textdomain' )
				);
			}
		}

		return $settings;
	}
}
```
Hopefully this helps the next person who ends up debugging downloads under WooCommerce!
