### ISSUE TITLE
Deprecating manual-install.zip

### ISSUE THREAD

**Issue by rmccue** [humanmade/S3-Uploads#644]
We get a lot of issues around the use of manual-install.zip with various small bugs, breakages in the build system, and confusion around it. This isn't something that we use at HM, and it shows - this is why our [support policy](https://engineering.hmn.md/projects/support/#our-promise) states that we use what we ship, as if this was broken for us, it'd be fixed in a matter of hours.

Right now, it's a poor experience for anyone trying to install the plugin, and isn't meeting our standards. As a result, we're going to remove this, and require the use of Composer.

If anyone in the community would like to pick up maintaining this, you're welcome to start a third-party repo that handles builds :) ([Here's the old workflow](https://github.com/humanmade/S3-Uploads/blob/44477a9bfa1732bd063bc1fc9e40719282860d42/.github/workflows/build-release.yml) for your reference.)

**Comment by wwwXpert** [comment]
That's unfortunate. I've been using this for a few years without issue. Most of the issues aren't due to the plug-in itself but to a combination of things, e.g. PHP function version deprecation, AWS permissions / settings, file system permission, configs, conflicts, etc...

**Comment by rmccue** [comment]
Appreciate the feedback here.

We'll aim not to intentionally break compatibility with anyone who wants to manually install the plugin and the SDK, and we won't require installation via Composer at the project (WordPress-wide) level. If you're not using Composer for everything else, installation into your plugins directory should be as simple as:

```sh
git clone https://github.com/humanmade/S3-Uploads.git s3-uploads
cd s3-uploads
composer install
```

(And `require`ing the autoload file.)

But we'll no longer provide a prebuilt zip with this bundled, and you'll be using it this way at your own (and higher) risk. :)

**Comment by kresnasatya** [comment]
I test in my local environment, I also get the issue cannot install `s3-uploads` plugin provided by Humanmade with WP CLI.

![image](https://github.com/humanmade/S3-Uploads/assets/11099186/6f7e92b8-806b-4e08-8ffc-1bd2e1ed9cab)

I'm using WordPress version 6.3 with PHP 8.2 (Laragon).

After do some tweaks by fork this repository, now I can install `s3-uploads` plugin with WP CLI. Here are some tweaks I do.

1. Update version phpunit/phpunit to version ^9.0.
2. Remove pcov/clobber because the coverage test has been include with phpunit/phpunit.
3. Update GitHub workflow by update PHP version to 8.2 and update ramsey/composer-install to version 2.

Here's my fork repository: https://github.com/kresnasatya/S3-Uploads/tree/update-dev-deps

Here's my command to install updated `s3-uploads` plugin with WP CLI.

```bash
wp plugin install https://github.com/kresnasatya/S3-Uploads/releases/latest/download/s3-uploads.zip --force
wp plugin activate s3-uploads
wp s3-uploads verify
```
![image](https://github.com/humanmade/S3-Uploads/assets/11099186/bd0cdb11-6186-4fc2-82e3-c362032fc1f1)

**Comment by rmccue** [comment]
This has been merged, and the only supported installation method now is via Composer.

**Comment by chrillep** [comment]
@rmccue @joehoyle are you going to tag a new release ?

**Comment by pentatonicfunk** [comment]
i think we can have little bit compromise here, idea:
- in `init()` introduce new hook, something like `s3_uploads_pre_init`
- Then user can download the plugin as is without modification. and to requires their own aws sdk, user can create mu-plugin that utilizing  `s3_uploads_pre_init` hook.
