### ISSUE TITLE
Multisite Network Support?

### ISSUE THREAD

**Issue by asifk6820** [humanmade/S3-Uploads#658]
I want to add Multisite Network Support since my the implementation is working for the main site only .
for my other site the implementation is not working.

Any ideas? Love the plugin, really hoping we can get this working!!

**Comment by joehoyle** [comment]
Hi there,Have you network activated the plugin? There should be no problem with using it on multi site On Dec 5, 2023, at 08:46, asifk6820 ***@***.***> wrote:﻿
I want to add Multisite Network Support since my the implementation is working for the main site only .
for my other site the implementation is not working.
Any ideas? Love the plugin, really hoping we can get this working!!

**Comment by asifk6820** [comment]
Hi Joe, Do I need to do some other changes since I have done the changes as per the readme file https://github.com/humanmade/S3-Uploads#readme and here no changes were mentioned for the multisite?

**Comment by joehoyle** [comment]
@asifk6820 the only difference is `wp plugin activate S3-Uploads`. If you are on multisite, and you want the it to be active on all sites, you'd need to do `wp plugin activate S3-Uploads --network`, or activate the plugin in the multisite network plugins page.

**Comment by asifk6820** [comment]
hi @joehoyle , it worked but all the images for the the sites are getting stored in the same folder only I want to store my images like below  :
 if there are two multisite site1 and site2  in s3 it should store in two folders like site1 and site2

**Comment by joehoyle** [comment]
@asifk6820 it should use the same layout as WordPress, so `uploads/sites/2/` for example.

**Comment by asifk6820** [comment]
Hi @joehoyle , it is really helpful 
thanks for the help it resolve my issue.
