### ISSUE TITLE
Migrates WP Offload S3 to S3 Uploads

### ISSUE THREAD

**Issue by jeffesonmaia** [humanmade/S3-Uploads#99]
On my website I use WP Offload S3 and when configured forgot to disable the object versioning and now that decides to change to S3 uploads discovered this problem. It creates a folder with timestamps before placing the image.

Example
wp-content/uploads/sites/2/2016/05/02165751/image.jpg

Any tips on how to solve it for the old images?

**Comment by joehoyle** [comment]
Hmm I'm not sure exactly what you mean. Object versioning in S3 Buckets shouldn't change the paths of files, is that a different WP Offload S3 thing maybe?

**Comment by joehoyle** [comment]
Closing due to no response.

**Comment by adambiggs** [comment]
@joehoyle I just ran into this problem as well. The WP Offload S3 plugin has an "Object Versioning" setting (not to be confused with AWS S3 object versioning) that prefixes image paths with a timestamp:

Turned on: `https://s3.amazonaws.com/my-bucket/wp‑content/uploads/2018/03/21221643/photo.jpg`
Turned off: `https://s3.amazonaws.com/my-bucket/wp‑content/uploads/2018/03/photo.jpg`

I'm currently trying to migrate to S3-Uploads, but all my old images are broken because the timestamp is missing from their URLs. Is there any way of fixing this?

**Comment by sirtawast** [comment]
Late on the game, you can make a shell script pretty easily to copy all the files to local disk using the AWS CLI like `aws s3 sync s3://bucket/ ./my-local-uploads/`. Then, [recursively move](https://superuser.com/questions/482632/how-to-recursively-move-all-folders-one-directory-up-back-one-directory/482644) files one directory up so you would have the WP default structure again. 

Beware, I am not sure if there is some version conflicts on same  name image uploads but I'm pretty sure you can just overwrite with the newest one during copy or rsync.
